# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Seqre < Formula
  desc "Self-hostable collection of everyday utilities - URL shortening, IP lookup, and secret sharing"
  homepage "https://github.com/piheta/seq.re"
  version "0.5.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/piheta/seq.re/releases/download/v0.5.0/seq.re_0.5.0_darwin_amd64.tar.gz"
      sha256 "e7b7f0b0c0460bfcee278d620eefc50c71cbf52dc8a4853c9b0f70ed7b39c521"

      def install
        bin.install "seqre"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/piheta/seq.re/releases/download/v0.5.0/seq.re_0.5.0_darwin_arm64.tar.gz"
      sha256 "9d14d2eed0d65a3c9d57c7236a7f6ba7b0c9173f41cefa95ea90fc2193ede150"

      def install
        bin.install "seqre"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/piheta/seq.re/releases/download/v0.5.0/seq.re_0.5.0_linux_amd64.tar.gz"
      sha256 "cb6b7f9edae6eb0aecedcc100f21e0fb3581b539be9975a0e0dd2d268691fcb8"
      def install
        bin.install "seqre"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/piheta/seq.re/releases/download/v0.5.0/seq.re_0.5.0_linux_arm64.tar.gz"
      sha256 "6bd960e2e19cba42528456887da76a083d2234da1eb16c18d74d7c6dbc0f590a"
      def install
        bin.install "seqre"
      end
    end
  end

  test do
    system "#{bin}/seqre", "--help"
  end
end
