# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Seqre < Formula
  desc "Self-hostable collection of everyday utilities - URL shortening, IP lookup, and secret sharing"
  homepage "https://github.com/piheta/seq.re"
  version "0.9.6"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/piheta/seq.re/releases/download/v0.9.6/seq.re_0.9.6_darwin_amd64.tar.gz"
      sha256 "fdcd16b37464bfecdea6091a8f66a1e8082dc3ac41ad6298ce5f593a87ef6b0b"

      def install
        bin.install "seqre"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/piheta/seq.re/releases/download/v0.9.6/seq.re_0.9.6_darwin_arm64.tar.gz"
      sha256 "4454475b672364c14859f0eb8266dcb14f2c36d5b86a407c0c15858968de0789"

      def install
        bin.install "seqre"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/piheta/seq.re/releases/download/v0.9.6/seq.re_0.9.6_linux_amd64.tar.gz"
      sha256 "fc9d308e65a656f615ada189ba1c6c28d94ce7cff77b553d6816d115eb2b2239"
      def install
        bin.install "seqre"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/piheta/seq.re/releases/download/v0.9.6/seq.re_0.9.6_linux_arm64.tar.gz"
      sha256 "146e971cc0cd458af1b8166af8455b19980a471fd796c49b898a34fe44ccc6de"
      def install
        bin.install "seqre"
      end
    end
  end

  test do
    system "#{bin}/seqre", "--help"
  end
end
